// network availability
export const NETWORK_CONNECTION_AVAILABILITY = 'NETWORK_CONNECTION_AVAILABILITY';
// authorized user
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_MESSAGE_DELETE = 'AUTH_MESSAGE_DELETE';

export const PROFILE_UPDATE_START = 'PROFILE_UPDATE_START';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';
export const PROFILE_UPDATE_LP_DISMISS = 'PROFILE_UPDATE_LP_DISMISS';
export const PROFILE_UPDATE_LP = 'PROFILE_UPDATE_LP';
export const PROFILE_FETCH_START = 'PROFILE_FETCH_START';
export const PROFILE_FETCH_FINISHED = 'PROFILE_FETCH_FINISHED';
export const PROFILE_FETCH_ERROR = 'PROFILE_FETCH_ERROR';

// dashboard
export const ADVERTISE_ITEMS_FETCH_UPLOAD_START = 'ADVERTISE_ITEMS_FETCH_UPLOAD_START';
export const ADVERTISE_ITEMS_FETCH_UPLOAD_SUCCESS = 'ADVERTISE_ITEMS_FETCH_UPLOAD_SUCCESS';
export const ADVERTISE_USER_ITEMS_FETCH_UPLOAD_SUCCESS = 'ADVERTISE_USER_ITEMS_FETCH_UPLOAD_SUCCESS';
export const ADVERTISE_ITEMS_FETCH_UPLOAD_ERROR = 'ADVERTISE_ITEMS_FETCH_UPLOAD_ERROR';
export const ADVERTISE_ITEMS_FETCH_UPLOAD_LP_DISMISS = 'ADVERTISE_ITEMS_FETCH_UPLOAD_LP_DISMISS';
export const ADVERTISE_ITEMS_FETCH_UPLOAD_LP = 'ADVERTISE_ITEMS_FETCH_UPLOAD_LP';

// normal user
export const ADVERTISES_FETCH_START = 'ADVERTISES_FETCH_START';
export const ADVERTISES_FETCH_SUCCESS = 'ADVERTISES_FETCH_SUCCESS';
export const ADVERTISES_FETCH_ERROR = 'ADVERTISES_FETCH_ERROR';
export const SINGLE_ADVERTISE_FETCH_SUCCESS = 'SINGLE_ADVERTISE_FETCH_SUCCESS';
export const SINGLE_PURCHASE_ADVERTISE_SUCCESS = 'SINGLE_PURCHASE_ADVERTISE_SUCCESS';

// subscription packages
export const SUB_PACKAGES_FETCH_START = 'SUB_PACKAGES_FETCH_START';
export const POST_SUB_PACKAGES_FETCH_SUCCESS = 'POST_SUB_PACKAGES_FETCH_SUCCESS';
export const GET_SUB_PACKAGES_FETCH_SUCCESS = 'GET_SUB_PACKAGES_FETCH_SUCCESS';
export const SELECT_SUB_PACKAGES_SUCCESS = 'SELECT_SUB_PACKAGES_SUCCESS';
export const SUB_PACKAGES_FETCH_FAIL = 'SUB_PACKAGES_FETCH_FAIL';
